name: Build and Release

on:
    push:
        branches:
            - main

jobs:
    build-and-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: 21

            - name: Grant execute permissions for gradlew
              run: chmod +x gradlew

            - name: Build with Gradle
              run: ./gradlew clean build

            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                  name: "Automated Release - ${{ github.sha }}"
                  tag_name: "build-${{ github.run_number }}"
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Upload Artifacts
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      bootstrap/bungeecord/build/libs/Geyser-BungeeCord.jar
                      bootstrap/mod/fabric/build/libs/Geyser-Fabric.jar
                      bootstrap/mod/neoforge/build/libs/Geyser-NeoForge.jar
                      bootstrap/spigot/build/libs/Geyser-Spigot.jar
                      bootstrap/standalone/build/libs/Geyser-Standalone.jar
                      bootstrap/velocity/build/libs/Geyser-Velocity.jar
                      bootstrap/viaproxy/build/libs/Geyser-ViaProxy.jar
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
